/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package POO;

import javax.swing.ImageIcon;

/**
 *
 * @author Humberto-PC
 */
public class Carte extends javax.swing.JPanel {

    //proprietés de la classe Carte
    private String urlFace;
    private String urlDos;
    private int id;

    //constructor
    public Carte(String urlFace, String urlDos, int id) {
        this.urlFace = urlFace;
        this.urlDos = urlDos;
        this.id = id;
        initComponents();
    }
    
    //getters & setters
    public String getUrlFace() {
        return urlFace;
    }

    public void setUrlFace(String urlFace) {
        this.urlFace = urlFace;
    }

    public String getUrlDos() {
        return urlDos;
    }

    public void setUrlDos(String urlDos) {
        this.urlDos = urlDos;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
    
    
    //méthodes
    public void affichePhoto() {
        ImageIcon icon = new ImageIcon(urlFace);
        photoLbl.setIcon(icon);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoLbl = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(125, 250));

        photoLbl.setPreferredSize(new java.awt.Dimension(123, 246));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(photoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(photoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel photoLbl;
    // End of variables declaration//GEN-END:variables
}
